### ISSUE TITLE
Use endsWith() for a more generic 'if' clause

### ISSUE THREAD

**Issue by brettcannon** [deadsnakes/action#2]
I think you can use https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#endswith to make the 'if' clause more generic and thus not require editing if one were to add e.g. "3.10-dev" in the future.

**Comment by asottile** [comment]
not sure what you mean? https://github.com/deadsnakes/action/blob/aa069b95d6b8757480f3bd10a23176907886aff9/index.js#L10

**Comment by asottile** [comment]
ohhhhh in the example, got it -- yeah that is a good idea

**Comment by asottile** [comment]
one downside is the quoting and it doesn't work for `3.9` (instead of 3.9-dev) but I imagine most will be using the `-dev` ones anyway

https://github.com/deadsnakes-issues-bot/test/blob/6e85df12fafc05c526074e87fed9cc80fa41887b/.github/workflows/blank.yml#L14

**Comment by brettcannon** [comment]
Yeah, I expect most people will use this for nightly and `-dev` builds.
